version: '3'
services:
  api:
    build:
      context: .
      dockerfile: ./docker_configs/Dockerfile.develop
    container_name: my-app-api
    tty: true
    stdin_open: true
    volumes:
      - .:/usr/app
      - node-modules:/usr/app/node_modules
    command: yarn run dev:api
    environment:
      - 'TZ=Asia/Tokyo'
    ports:
      - '4000:4000'
      - '3000:3000'
  prisma:
    image: prismagraphql/prisma:1.10
    container_name: my-app-prisma
    restart: always
    ports:
      - "4466:4466"
    depends_on:
      - mysql
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: root
            password: prisma
            migrations: true
  mysql:
    image: mysql:5.7
    container_name: my-app-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:
  node-modules:
