projects:
  app:
    schemaPath: src/schema.graphql
    includes: ["src/**/*.graphql"]
    extensions:
      endpoints:
        default: http://localhost:4000
      codegen:
        - generator: graphql-binding
          language: typescript
          input:
            schema: src/schema.ts
          output:
            binding: src/generated/api.ts
  database:
    schemaPath: src/generated/prisma.graphql
    extensions:
      prisma: database/prisma.yml
      codegen:
        - generator: prisma-binding
          language: typescript
          output:
            binding: src/generated/prisma.ts
